manifest_version = 1

[module]
name = "Nebulus: Manager"
id = "nebulus_manager"
description = "The basics of Nebulus control"
version = "1.0.0"
license = "MIT"
authors = ["ItsMeAlfie0"]
requirements = ["psycopg2-binary==2.9.6"]
